# -*- coding: utf-8 -*-
"""Data Preprocessing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BKEb9OL-JIit39fzAFP5DbyP9b5WyO_j
"""

!pip install yfinance

pip install yahoo_fin --upgrade

import pandas as pd
import numpy as np
import yfinance 
import yahoo_fin.stock_info as si
import matplotlib.pyplot as plt
from scipy.stats import skew,kurtosis,norm,skewtest,kurtosistest
from statsmodels.graphics.tsaplots import plot_pacf,plot_acf

import yfinance as yf

import pandas.util.testing as tm

pip install requests_html

stock_list = ['ADANIPORTS.NS','ARVIND.NS', 'ASIANPAINT.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BHARTIARTL.NS', 'BPCL.NS', 'BRITANNIA.NS','CIPLA.NS', 'COALINDIA.NS', 'DIVISLAB.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'GILLETTE.NS', 'GOKEX.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFC.NS', 'HDFCBANK.NS', 'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDUNILVR.NS', 'IBREALEST.NS', 'ICICIBANK.NS', 'INDUSINDBK.NS', 'INFY.NS', 'IOC.NS',  'ITC.NS', 'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LT.NS', 'M&M.NS', 'MARUTI.NS', 'NESTLEIND.NS', 'NTPC.NS', 'ONGC.NS', 'POWERGRID.NS', 'RELIANCE.NS', 'SBIN.NS', 'SBILIFE.NS', 'SHREECEM.NS', 'SUNPHARMA.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS',  'TCS.NS', 'TATACONSUM.NS', 'TECHM.NS', 'TITAN.NS', 'ULTRACEMCO.NS', 'UPL.NS','WIPRO.NS']

dow_stats = {}
for ticker in stock_list:
    temp = si.get_stats_valuation(ticker)
    temp = temp.iloc[:,:2]
    temp.columns = ["Attribute", "Recent"]
    dow_stats[ticker] = temp
dow_stats

combined_stats = pd.concat(dow_stats)
combined_stats = combined_stats.reset_index()
combined_stats

del combined_stats["level_1"]
# update column names
combined_stats.columns = ["Ticker", "Attribute", "Recent"]
combined_stats

markcap = combined_stats[combined_stats["Attribute"]=="Market Cap (intraday)"].reset_index()
markcap

del markcap["index"]

del markcap["Attribute"]
markcap.columns = ["Ticker", "Market Cap"]
markcap

markcap[["Market Cap"]] = markcap[["Market Cap"]].apply(lambda x: x.str.replace('.','', regex=True))
markcap[["Market Cap"]] = markcap[["Market Cap"]].apply(lambda x: x.str.replace('T','0000000000', regex=True))
markcap[["Market Cap"]] = markcap[["Market Cap"]].apply(lambda x: x.str.replace('B','0000000', regex=True))
markcap

markcap[["Market Cap"]] = markcap[["Market Cap"]].apply(pd.to_numeric)
markcap

markcap['Class'] = np.where(markcap['Market Cap'] >= 200000000000, 'Large-cap', 'Mid-cap')
markcap